sudo: required
services:
  - docker 

before_install:
  - docker build -t ashishdhawal/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ashishdhawal/docker-react npm run test 

deploy:
  provider: azure_web_apps
  region: "Central US"
  app: "docker-reactajd"
  site: "docker-reactajd.azurewebsites.net"
  on:
    branch: master
username: "$azure_deployment_user"
password: "$azure_deployment_password"