sudo: required
services:
  - docker 

before_install:
  - docker build -t ashishdhawal/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ashishdhawal/docker-react npm run test 

deploy:
  provider: azure_web_apps
  region: "Central US"
  app: "docker-reactajd"
  site: "https://docker-reactajd.azurewebsites.net"
  username: "AZURE_DEPLOYMENT_USER"
  password: "AZURE_DEPLOYMENT_PASSWORD"